import Navbar from "../components/navbar";
import Footer from "../components/footer";
import ClientProvider from "../components/ClientProvider";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <ClientProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </ClientProvider>
        </body>
      </UserProvider>
    </html>
  );
}
