import NavbarWrapper from "@/components/server/navbar-wrapper";
import FooterWrapper from "@/components/server/footer-wrapper";
import ClientProvider from "@/components/client/ClientProvider";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <ClientProvider>
            <NavbarWrapper />
            <main>{children}</main>
            <FooterWrapper />
          </ClientProvider>
        </body>
      </UserProvider>
    </html>
  );
}
